package com.banula.ocpi.model.enums;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum TokenType {
    /**
     * One time use Token ID generated by a server (or App.) The eMSP uses this to bind a Session to a
     * customer, probably an app user.
     */
    @JsonProperty("AD_HOC_USER")
    AD_HOC_USER,
    /**
     * Token ID generated by a server (or App.) to identify a user of an App. The same user uses the
     * same Token for every Session.
     */
    @JsonProperty("APP_USER")
    APP_USER,
    /**
     * Other type of token
     */
    @JsonProperty("OTHER")
    OTHER,
    /**
     * RFID Token
     */
    @JsonProperty("RFID")
    RFID
}
